### ISSUE TITLE
First issue


### ISSUE THREAD

**Issue by priyansh2003** [priyansh2003/SDSLABS-FINAL-PROJECT#1]

**Comment by ayush-dudhani** [comment]
What's the issue?

**Comment by priyansh2003** [comment]
Dude I was just testing how to contribute with a friend so I created a fake
issue. Closing it. 😂 thanks for the concern man! Appreciate that

**Comment by ayush-dudhani** [comment]
Okay, well I am also new to Open Source. So was just searching for some issues where I can contribute.

**Comment by priyansh2003** [comment]
Same buddy I am also new to this open source thing.
